// ide-symbol-index Unit 4 — stdlib source extraction (spec §6.0.3).
//
// The stdlib source is embedded in the compiler binary (cajeta::stdlib::g_files,
// generated by cmake/EmbedStdlib.cmake) and until now had no way out. The IDE
// plugin needs it on disk to mount and index, so debug stops and navigation into
// stdlib frames land in real files.
//
//   cajeta stdlib list             one embedded relative path per line, stdout
//   cajeta stdlib extract <dir>    write the tree under <dir>, preserving
//                                  package paths, plus an identity marker
//                                  (.cajeta-stdlib.json) keyed to the compiler
//
// Pins (plan 4.1.1 - 4.1.4, 4.2.2):
//   4.1.1  extraction preserves package paths (cajeta/lang/Object.cajeta).
//   4.1.2  extracted set == listed set — count and content.
//   4.1.3  list mode reports the set without writing anything.
//   4.1.4  extraction is idempotent and leaves unrelated files alone.
//   4.2.2  the identity marker carries the producing compiler's version, so the
//          plugin can key its cache and re-extract on compiler change.

#include <gtest/gtest.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <random>
#include <set>
#include <sstream>
#include <string>
#include "../PortableEnv.h"

namespace fs = std::filesystem;

namespace {

#ifdef _WIN32
#  define CAJETA_SLX_DEVNULL "NUL"
#else
#  define CAJETA_SLX_DEVNULL "/dev/null"
#endif

    std::string sourceRoot() {
        const char* envRoot = std::getenv("CAJETA_SOURCE_ROOT");
        if (envRoot && *envRoot) return envRoot;
#ifdef CAJETA_SOURCE_ROOT_DEFAULT
        return CAJETA_SOURCE_ROOT_DEFAULT;
#else
        return ".";
#endif
    }

    std::string compilerBinary() {
        std::string b = sourceRoot() + "/build/src/cajeta";
#ifdef _WIN32
        b += ".exe";   // is_regular_file() guard needs the real name
#endif
        return b;
    }

    fs::path freshTempDir(const std::string& tag) {
        static std::mt19937_64 rng(std::random_device{}());
        auto base = fs::temp_directory_path()
                  / ("cajeta_slx_" + tag + "_" + std::to_string(rng()));
        fs::create_directories(base);
        return base;
    }

    // Run the binary with `args`; capture stdout and stderr separately.
    // Returns the exit code (-1 if the binary is missing).
    int runCajeta(const std::string& args, std::string& out, std::string& err) {
        auto bin = compilerBinary();
        if (!fs::exists(bin)) return -1;
        auto dir = freshTempDir("io");
        auto outFile = dir / "stdout.txt";
        auto errFile = dir / "stderr.txt";
        std::string cmd = bin + " " + args
                        + " > " + outFile.string() + " 2> " + errFile.string();
        int rc = std::system(cajeta_shell(cmd).c_str());
        std::ifstream fo(outFile), fe(errFile);
        out.assign((std::istreambuf_iterator<char>(fo)),
                    std::istreambuf_iterator<char>());
        err.assign((std::istreambuf_iterator<char>(fe)),
                    std::istreambuf_iterator<char>());
#ifdef _WIN32
        return rc;
#else
        return WEXITSTATUS(rc);
#endif
    }

    std::string slurp(const fs::path& p) {
        std::ifstream f(p, std::ios::binary);
        return std::string((std::istreambuf_iterator<char>(f)),
                            std::istreambuf_iterator<char>());
    }

    std::set<std::string> listedPaths(const std::string& stdoutText) {
        std::set<std::string> paths;
        std::istringstream in(stdoutText);
        for (std::string line; std::getline(in, line); ) {
            if (!line.empty()) paths.insert(line);
        }
        return paths;
    }

    // Every extracted .cajeta under root, as /-separated paths relative to root.
    std::set<std::string> extractedPaths(const fs::path& root) {
        std::set<std::string> paths;
        for (auto& e : fs::recursive_directory_iterator(root)) {
            if (!e.is_regular_file()) continue;
            if (e.path().extension() != ".cajeta") continue;
            paths.insert(fs::relative(e.path(), root).generic_string());
        }
        return paths;
    }

} // namespace

// ---- 4.1.3 — list mode -------------------------------------------------------

TEST(StdlibExtract, ListReportsTheEmbeddedSetOnStdout) {
    std::string out, err;
    int rc = runCajeta("stdlib list", out, err);
    ASSERT_NE(rc, -1) << "compiler binary missing";
    EXPECT_EQ(rc, 0) << err;

    auto paths = listedPaths(out);
    // The embedded set is the whole stdlib — hundreds of files, all .cajeta,
    // all package-pathed. Pin shape, not an exact count that drifts with
    // every stdlib addition.
    EXPECT_GT(paths.size(), 100u);
    EXPECT_TRUE(paths.count("cajeta/lang/Object.cajeta")) << out.substr(0, 400);
    for (const auto& p : paths) {
        EXPECT_NE(p.rfind(".cajeta"), std::string::npos) << p;
        EXPECT_EQ(p.rfind("cajeta/", 0), 0u) << p << " is not package-pathed";
    }
}

// ---- 4.1.1 / 4.1.2 — extraction matches the embedded set ----------------------

TEST(StdlibExtract, ExtractWritesTheListedSetPreservingPackagePaths) {
    auto dir = freshTempDir("tree");

    std::string listOut, out, err;
    ASSERT_EQ(runCajeta("stdlib list", listOut, err), 0) << err;
    int rc = runCajeta("stdlib extract " + dir.string(), out, err);
    ASSERT_NE(rc, -1) << "compiler binary missing";
    EXPECT_EQ(rc, 0) << err;

    // 4.1.1 — package paths preserved.
    EXPECT_TRUE(fs::exists(dir / "cajeta/lang/Object.cajeta"));

    // 4.1.2 — the extracted set IS the listed set, exactly.
    EXPECT_EQ(extractedPaths(dir), listedPaths(listOut));
}

TEST(StdlibExtract, ExtractedContentIsByteIdenticalToTheRuntimeSource) {
    // The embed is generated from runtime/src (src/CMakeLists.txt); with a
    // current build the extracted bytes must round-trip exactly. Also plan
    // acceptance 4.3.1 for ArrayList specifically.
    auto dir = freshTempDir("bytes");
    std::string out, err;
    ASSERT_EQ(runCajeta("stdlib extract " + dir.string(), out, err), 0) << err;

    for (const char* rel : { "cajeta/lang/Object.cajeta",
                             "cajeta/collection/ArrayList.cajeta" }) {
        auto extracted = dir / rel;
        auto original  = fs::path(sourceRoot()) / "runtime/src" / rel;
        ASSERT_TRUE(fs::exists(extracted)) << rel;
        ASSERT_TRUE(fs::exists(original)) << rel;
        EXPECT_EQ(slurp(extracted), slurp(original)) << rel;
    }
}

// ---- 4.1.4 — idempotent, and no collateral damage ------------------------------

TEST(StdlibExtract, ExtractionIsIdempotentAndPreservesUnrelatedFiles) {
    auto dir = freshTempDir("idem");

    // Unrelated files both beside and inside the extraction tree.
    std::ofstream(dir / "notes.txt") << "mine\n";
    fs::create_directories(dir / "cajeta/lang");
    std::ofstream(dir / "cajeta/lang/scratch.txt") << "also mine\n";

    std::string out, err;
    ASSERT_EQ(runCajeta("stdlib extract " + dir.string(), out, err), 0) << err;
    auto firstObject = slurp(dir / "cajeta/lang/Object.cajeta");

    ASSERT_EQ(runCajeta("stdlib extract " + dir.string(), out, err), 0) << err;

    EXPECT_EQ(slurp(dir / "cajeta/lang/Object.cajeta"), firstObject);
    EXPECT_EQ(slurp(dir / "notes.txt"), "mine\n");
    EXPECT_EQ(slurp(dir / "cajeta/lang/scratch.txt"), "also mine\n");
}

// ---- 4.2.2 — the identity marker ----------------------------------------------

TEST(StdlibExtract, ExtractionWritesACompilerKeyedIdentityMarker) {
    auto dir = freshTempDir("ident");
    std::string out, err;
    ASSERT_EQ(runCajeta("stdlib extract " + dir.string(), out, err), 0) << err;

    auto marker = dir / ".cajeta-stdlib.json";
    ASSERT_TRUE(fs::exists(marker));
    auto text = slurp(marker);
    EXPECT_NE(text.find("\"version\""), std::string::npos) << text;
    EXPECT_NE(text.find("\"gitHash\""), std::string::npos) << text;
    EXPECT_NE(text.find("\"fileCount\""), std::string::npos) << text;

    // The count in the marker is the listed count — the plugin trusts it to
    // detect a torn extraction.
    std::string listOut;
    ASSERT_EQ(runCajeta("stdlib list", listOut, err), 0) << err;
    EXPECT_NE(text.find("\"fileCount\": "
                        + std::to_string(listedPaths(listOut).size())),
              std::string::npos) << text;
}

// ---- usage --------------------------------------------------------------------

TEST(StdlibExtract, MissingOrUnknownVerbFailsWithUsage) {
    std::string out, err;
    EXPECT_NE(runCajeta("stdlib", out, err), 0);
    EXPECT_NE(err.find("Usage"), std::string::npos) << err;

    EXPECT_NE(runCajeta("stdlib frobnicate", out, err), 0);
    EXPECT_NE(runCajeta("stdlib extract", out, err), 0)
        << "extract with no target directory must be refused";
}
