// SkillEmbed — build-time codegen for the cajeta stdlib skill corpus.
//
// Packs every runtime/src/cajeta/<pkg>/skills/*.md and
// runtime/skills/<domain>/*.md into a single
// zstd-compressed blob and emits a .cpp defining
// cajeta::stdlib::g_stdlibSkillsCompressed (+ lengths). The compiler/build-tool
// decompresses it on first skill access (EmbeddedStdlibSkills.cpp) so the
// stdlib's skills are always available with no .cja / lockfile, while the
// binary carries them compressed (skill-discovery spec §2.4/§2.5).
//
// Blob framing (little-endian), then zstd-compressed whole:
//   u32 count
//   count × { u32 libLen, lib bytes, u32 contentLen, content bytes }
// `lib` is the library coordinate "cajeta.<pkg>" derived from the path.

#include <zstd.h>

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

    std::string readFile(const std::string& path) {
        std::ifstream in(path, std::ios::binary);
        std::ostringstream ss;
        ss << in.rdbuf();
        return ss.str();
    }

    void putU32(std::string& b, uint32_t v) {
        b.push_back((char) (v & 0xff));
        b.push_back((char) ((v >> 8) & 0xff));
        b.push_back((char) ((v >> 16) & 0xff));
        b.push_back((char) ((v >> 24) & 0xff));
    }

    std::vector<std::string> splitSlash(const std::string& s) {
        std::vector<std::string> parts;
        std::string cur;
        for (char c : s) {
            if (c == '/') { parts.push_back(cur); cur.clear(); }
            else cur.push_back(c);
        }
        if (!cur.empty()) parts.push_back(cur);
        return parts;
    }

    // "cajeta/<pkg>/skills/<id>.md" (relative to runtime/src) -> "cajeta.<pkg>".
    std::string libFromRel(const std::string& rel) {
        auto parts = splitSlash(rel);
        if (parts.size() >= 2 && parts[0] == "cajeta") return "cajeta." + parts[1];
        return parts.empty() ? std::string("cajeta") : parts[0];
    }

    std::string relativeTo(const std::string& root, const std::string& path) {
        std::string r = root;
        if (!r.empty() && r.back() != '/') r.push_back('/');
        if (path.rfind(r, 0) == 0) return path.substr(r.size());
        return path;
    }

} // namespace

int main(int argc, char** argv) {
    if (argc < 4) {
        std::fprintf(stderr, "usage: skillembed <manifest> <stdlibRoot> <out.cpp>\n");
        return 2;
    }
    const std::string manifest = argv[1], root = argv[2], out = argv[3];

    // Manifest line: `<path>` (library derived from the path under root) or
    // `<library>\t<path>` (explicit — runtime/skills/<domain> corpus entries).
    std::vector<std::pair<std::string, std::string>> entries; // {lib, path}
    {
        std::ifstream in(manifest);
        std::string line;
        while (std::getline(in, line)) {
            if (!line.empty() && line.back() == '\r') line.pop_back();
            if (line.empty()) continue;
            auto tab = line.find('\t');
            if (tab == std::string::npos) {
                entries.emplace_back(libFromRel(relativeTo(root, line)), line);
            } else {
                entries.emplace_back(line.substr(0, tab), line.substr(tab + 1));
            }
        }
    }

    std::string blob;
    putU32(blob, (uint32_t) entries.size());
    for (const auto& [lib, p] : entries) {
        const std::string content = readFile(p);
        putU32(blob, (uint32_t) lib.size());
        blob += lib;
        putU32(blob, (uint32_t) content.size());
        blob += content;
    }

    std::vector<unsigned char> comp;
    if (!blob.empty()) {
        size_t bound = ZSTD_compressBound(blob.size());
        comp.resize(bound);
        size_t n = ZSTD_compress(comp.data(), bound, blob.data(), blob.size(), 19);
        if (ZSTD_isError(n)) {
            std::fprintf(stderr, "skillembed: zstd compress failed: %s\n",
                         ZSTD_getErrorName(n));
            return 1;
        }
        comp.resize(n);
    }

    std::ofstream o(out, std::ios::binary);
    o << "// AUTO-GENERATED by tools/skillembed. Do not edit.\n";
    o << "#include <cstddef>\n\n";
    o << "namespace cajeta { namespace stdlib {\n\n";
    o << "extern const unsigned char g_stdlibSkillsCompressed[] = {";
    if (comp.empty()) {
        o << "0";   // keep the array non-empty (valid C++); len stays 0
    } else {
        for (size_t i = 0; i < comp.size(); ++i) {
            if (i % 20 == 0) o << "\n    ";
            o << (unsigned) comp[i] << ",";
        }
        o << "\n";
    }
    o << "};\n";
    o << "extern const size_t g_stdlibSkillsCompressedLen = " << comp.size() << ";\n";
    o << "extern const size_t g_stdlibSkillsUncompressedLen = " << blob.size() << ";\n\n";
    o << "}}  // namespace cajeta::stdlib\n";
    return 0;
}
