package dev.cajeta.idea.parser

import dev.cajeta.idea.parser.antlr.CajetaLexer
import org.antlr.v4.runtime.DefaultErrorStrategy
import org.antlr.v4.runtime.Parser
import org.antlr.v4.runtime.misc.IntervalSet

/**
 * Anchor-sync error recovery for IDE use. The default strategy
 * does single-token insertion/deletion, which produces noisy partial
 * trees mid-typing. Syncing to statement/block/declaration anchors
 * lets recoveries land on clean boundaries so the rest of the file
 * still parses.
 *
 * Maintenance: anchor token IDs reference constants generated by
 * ANTLR from CajetaLexer.g4. Adding or renaming a declaration
 * keyword in the grammar requires touching this list.
 */
class CajetaErrorStrategy : DefaultErrorStrategy() {

    private val anchorTokens: IntervalSet = IntervalSet(
        CajetaLexer.SEMI,
        CajetaLexer.RBRACE,
        CajetaLexer.LBRACE,
        CajetaLexer.PACKAGE,
        CajetaLexer.IMPORT,
        CajetaLexer.CLASS,
        CajetaLexer.INTERFACE,
        CajetaLexer.STRUCTURE,
        CajetaLexer.ENUM,
        CajetaLexer.PUBLIC,
        CajetaLexer.PRIVATE,
        CajetaLexer.PROTECTED,
        CajetaLexer.STATIC,
        CajetaLexer.FINAL,
        CajetaLexer.ABSTRACT,
    )

    override fun getErrorRecoverySet(recognizer: Parser): IntervalSet =
        super.getErrorRecoverySet(recognizer).or(anchorTokens)
}
