package dev.cajeta.idea.parser

import dev.cajeta.idea.parser.antlr.CajetaLexer
import org.antlr.v4.runtime.DefaultErrorStrategy
import org.antlr.v4.runtime.Parser
import org.antlr.v4.runtime.RecognitionException
import org.antlr.v4.runtime.misc.IntervalSet

/**
 * Anchor-sync error recovery for IDE use. The default strategy
 * does single-token insertion/deletion, which produces noisy partial
 * trees mid-typing. Syncing to statement/block/declaration anchors
 * lets recoveries land on clean boundaries so the rest of the file
 * still parses.
 *
 * Maintenance: anchor token IDs reference constants generated by
 * ANTLR from CajetaLexer.g4. Adding or renaming a declaration
 * keyword in the grammar requires touching this list.
 */
class CajetaErrorStrategy : DefaultErrorStrategy() {

    private val anchorTokens: IntervalSet = IntervalSet(
        CajetaLexer.SEMI,
        CajetaLexer.RBRACE,
        CajetaLexer.LBRACE,
        CajetaLexer.PACKAGE,
        CajetaLexer.IMPORT,
        CajetaLexer.CLASS,
        CajetaLexer.INTERFACE,
        CajetaLexer.STRUCTURE,
        CajetaLexer.ENUM,
        CajetaLexer.PUBLIC,
        CajetaLexer.PRIVATE,
        CajetaLexer.PROTECTED,
        CajetaLexer.STATIC,
        CajetaLexer.FINAL,
        CajetaLexer.ABSTRACT,
    )

    override fun getErrorRecoverySet(recognizer: Parser): IntervalSet =
        super.getErrorRecoverySet(recognizer).or(anchorTokens)

    /**
     * W4b telemetry: after the default recovery consumes up to a token in the
     * recovery set, record which token it landed on and whether that token is
     * one of our curated anchors. Lets us see how often recovery fires and
     * whether the anchor set covers where errors actually land.
     */
    override fun recover(recognizer: Parser, e: RecognitionException) {
        super.recover(recognizer, e)
        val landed = recognizer.currentToken?.type ?: return
        ErrorRecoveryTelemetry.record(landed, anchorTokens.contains(landed))
    }
}
