//
// stdlib-ownership-convention U4 — exception ctors take #String (4.1.4/4.2.2).
//
// One data-survival canary per migrated ctor. Shape: the message is a
// TEMPORARY (31-char literal + digit = 32 bytes, past the 24-byte SSO
// region so the concat carries a heap root), passed plainly. Before the
// migration the plain formal lends the temp, the ctor plain-stores the
// borrow, the temp frees at the statement end, and the exception's
// message field dangles — churn recycles the block and the readback
// mismatches. After the `#String` migration the temporary transfers into
// the ctor (the LtmPager throw-site precedent) and the store owns it.
//
// GENERATED by the inline generator in the commit that adds this file —
// one TEST per class so a future ctor regression names its class.
//

#include "gtest/gtest.h"
#include "../jit/JitTestHelper.h"

#include <cstdint>
#include <string>

using cajeta_test::CajetaJit;

namespace {

int32_t runI32(const std::string& src) {
    auto jit = CajetaJit::compile(src, "test.D");
    auto fn = jit->lookup<int32_t (*)()>("run");
    return fn ? fn() : -1;
}

std::string canary(const char* import_pkg, const char* cls,
                   const char* extraArgs) {
    std::string s;
    s += "package test;\n";
    s += std::string("import ") + import_pkg + "." + cls + ";\n";
    s += "public final class D {\n";
    s += std::string("    static #") + cls + " make(int32 i) {\n";
    s += std::string("        ") + cls + " e #= heap " + cls +
         "(\"0123456789012345678901234567890\" + i" + extraArgs + ");\n";
    s += "        return #= e;\n";
    s += "    }\n";
    s += "    public static int32 run() {\n";
    s += std::string("        ") + cls + " e #= D.make(7);\n";
    s += "        int32 j = 0;\n";
    s += "        while (j < 8) {\n";
    s += "            int8[] c = heap int8[32];\n";
    s += "            int32 k = 0;\n";
    s += "            while (k < 32) { c[k] = (int8) 90; k = k + 1; }\n";
    // Churn the String-object size class too: the dangling thing is the
    // plain-stored String OBJECT (plus its root); int8[] churn alone left
    // the freed object unrecycled and the canary read back intact.
    s += "            String cs = \"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ\" + j;\n";
    s += "            if (cs.byteLength() < 1) { return -9; }\n";
    s += "            j = j + 1;\n";
    s += "        }\n";
    s += "        String m = e.message;\n";
    s += "        if (m == null) { return -2; }\n";
    s += "        if (m.equals(\"01234567890123456789012345678907\")) { return 1; }\n";
    s += "        return 0;\n";
    s += "    }\n";
    s += "}\n";
    return s;
}

}  // namespace

TEST(ExceptionMessageOwnershipTests, CsvParseException) {
    EXPECT_EQ(1, runI32(canary("cajeta.codec.csv", "CsvParseException", ", (int64) 0")));
}

TEST(ExceptionMessageOwnershipTests, JsonParseException) {
    EXPECT_EQ(1, runI32(canary("cajeta.codec.json", "JsonParseException", ", (int64) 0")));
}

TEST(ExceptionMessageOwnershipTests, ClassCastException) {
    EXPECT_EQ(1, runI32(canary("cajeta.error", "ClassCastException", "")));
}

TEST(ExceptionMessageOwnershipTests, IfxException) {
    EXPECT_EQ(1, runI32(canary("cajeta.ifx", "IfxException", "")));
}

TEST(ExceptionMessageOwnershipTests, AlreadyExistsException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "AlreadyExistsException", "")));
}

TEST(ExceptionMessageOwnershipTests, CrossDeviceException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "CrossDeviceException", "")));
}

TEST(ExceptionMessageOwnershipTests, DiskFullException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "DiskFullException", "")));
}

TEST(ExceptionMessageOwnershipTests, EndOfFileException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "EndOfFileException", "")));
}

TEST(ExceptionMessageOwnershipTests, IoException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "IoException", "")));
}

TEST(ExceptionMessageOwnershipTests, IsDirectoryException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "IsDirectoryException", "")));
}

TEST(ExceptionMessageOwnershipTests, NotDirectoryException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "NotDirectoryException", "")));
}

TEST(ExceptionMessageOwnershipTests, NotFoundException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "NotFoundException", "")));
}

TEST(ExceptionMessageOwnershipTests, PermissionException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.file", "PermissionException", "")));
}

TEST(ExceptionMessageOwnershipTests, AddressInUseException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "AddressInUseException", "")));
}

TEST(ExceptionMessageOwnershipTests, AddressNotAvailableException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "AddressNotAvailableException", "")));
}

TEST(ExceptionMessageOwnershipTests, BrokenPipeException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "BrokenPipeException", "")));
}

TEST(ExceptionMessageOwnershipTests, ConnectionAbortedException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "ConnectionAbortedException", "")));
}

TEST(ExceptionMessageOwnershipTests, ConnectionRefusedException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "ConnectionRefusedException", "")));
}

TEST(ExceptionMessageOwnershipTests, ConnectionResetException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "ConnectionResetException", "")));
}

TEST(ExceptionMessageOwnershipTests, HostUnreachableException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "HostUnreachableException", "")));
}

TEST(ExceptionMessageOwnershipTests, MalformedAddressException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "MalformedAddressException", ", (int64) 0")));
}

TEST(ExceptionMessageOwnershipTests, NetException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "NetException", "")));
}

TEST(ExceptionMessageOwnershipTests, NetworkUnreachableException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "NetworkUnreachableException", "")));
}

TEST(ExceptionMessageOwnershipTests, TimedOutException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "TimedOutException", "")));
}

TEST(ExceptionMessageOwnershipTests, CertificateInvalidException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net.tls", "CertificateInvalidException", ", 0")));
}

TEST(ExceptionMessageOwnershipTests, TlsException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net.tls", "TlsException", "")));
}

TEST(ExceptionMessageOwnershipTests, TooManyConnectionsException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "TooManyConnectionsException", ", 0")));
}

TEST(ExceptionMessageOwnershipTests, MalformedUriException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net.uri", "MalformedUriException", ", (int64) 0")));
}

TEST(ExceptionMessageOwnershipTests, WouldBlockException) {
    EXPECT_EQ(1, runI32(canary("cajeta.io.net", "WouldBlockException", "")));
}

TEST(ExceptionMessageOwnershipTests, EncodingException) {
    EXPECT_EQ(1, runI32(canary("cajeta.lang", "EncodingException", ", (int64) 0, 0, 0, 0, \"reasonreasonreasonreasonreasonre\" + i")));
}

TEST(ExceptionMessageOwnershipTests, BroadcastException) {
    EXPECT_EQ(1, runI32(canary("cajeta.math", "BroadcastException", "")));
}

TEST(ExceptionMessageOwnershipTests, DistanceException) {
    EXPECT_EQ(1, runI32(canary("cajeta.math.distance", "DistanceException", "")));
}

TEST(ExceptionMessageOwnershipTests, LinAlgException) {
    EXPECT_EQ(1, runI32(canary("cajeta.math.linalg", "LinAlgException", "")));
}

TEST(ExceptionMessageOwnershipTests, OptimException) {
    EXPECT_EQ(1, runI32(canary("cajeta.math.optim", "OptimException", "")));
}

TEST(ExceptionMessageOwnershipTests, PlacementException) {
    EXPECT_EQ(1, runI32(canary("cajeta.math", "PlacementException", "")));
}

TEST(ExceptionMessageOwnershipTests, StatsException) {
    EXPECT_EQ(1, runI32(canary("cajeta.math.stats", "StatsException", "")));
}

TEST(ExceptionMessageOwnershipTests, ColumnTypeException) {
    EXPECT_EQ(1, runI32(canary("cajeta.nucleo.column", "ColumnTypeException", "")));
}

TEST(ExceptionMessageOwnershipTests, FrameException) {
    EXPECT_EQ(1, runI32(canary("cajeta.nucleo.frame", "FrameException", "")));
}

TEST(ExceptionMessageOwnershipTests, SparseException) {
    EXPECT_EQ(1, runI32(canary("cajeta.nucleo.sparse", "SparseException", "")));
}

TEST(ExceptionMessageOwnershipTests, DateTimeException) {
    EXPECT_EQ(1, runI32(canary("cajeta.time", "DateTimeException", "")));
}

TEST(ExceptionMessageOwnershipTests, DateTimeParseException) {
    EXPECT_EQ(1, runI32(canary("cajeta.time", "DateTimeParseException", ", (int64) 0")));
}

TEST(ExceptionMessageOwnershipTests, Base64Exception) {
    EXPECT_EQ(1, runI32(canary("cajeta.codec", "Base64Exception", ", (int64) 0")));
}
