// Rust sort competitors — sort 50K i64 across the SAME four input patterns the
// Cajeta side uses (random / ascending / descending / dups), plus a 50K f64
// random sort. One schema-conformant CSV row per (benchmark, variant, library).
// The input is generated by an identical splitmix64 sequence in every language,
// so all runners sort comparable data. Cross-check: output is non-decreasing and
// (for i64) the wrapping sum is preserved. Libraries: std sort_unstable
// (ipnsort) and std sort (driftsort, stable).
//
// Diagnostic note: Cajeta's Sort.sort overflows its 128-deep range stack on the
// adversarial patterns and records them as skips; these std sorts complete all
// four, so the report shows the variants Cajeta cannot yet do.
use std::time::Instant;
use std::alloc::{GlobalAlloc, Layout, System};
use std::sync::atomic::{AtomicU64, Ordering as _Ord};
static _ALLOCED: AtomicU64 = AtomicU64::new(0);
static _LAST: AtomicU64 = AtomicU64::new(0);
struct _Counting;
unsafe impl GlobalAlloc for _Counting {
    unsafe fn alloc(&self, l: Layout) -> *mut u8 { _ALLOCED.fetch_add(l.size() as u64, _Ord::Relaxed); System.alloc(l) }
    unsafe fn dealloc(&self, p: *mut u8, l: Layout) { System.dealloc(p, l) }
}
#[global_allocator]
static _GA: _Counting = _Counting;
fn _alloc_of<F: FnOnce()>(run: F) { _ALLOCED.store(0, _Ord::Relaxed); run(); _LAST.store(_ALLOCED.load(_Ord::Relaxed), _Ord::Relaxed); }
fn _la() -> u64 { _LAST.load(_Ord::Relaxed) }

const N: usize = 50_000;
const SEED: u64 = 0x1234_5678_9ABC_DEF0;

fn env(k: &str, d: &str) -> String { std::env::var(k).unwrap_or_else(|_| d.to_string()) }

fn peak_rss_kb() -> i64 {
    std::fs::read_to_string("/proc/self/status").ok().and_then(|s| {
        s.lines().find(|l| l.starts_with("VmHWM:"))
            .and_then(|l| l.split_whitespace().nth(1)).and_then(|v| v.parse().ok())
    }).unwrap_or(-1)
}

struct Split(u64);
impl Split {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
}

fn make_i64(variant: &str) -> Vec<i64> {
    let mut s = Split(SEED);
    (0..N).map(|i| match variant {
        "random" => s.next() as i64,
        "ascending" => i as i64,
        "descending" => (N - 1 - i) as i64,
        "dups" => (i % 16) as i64,
        _ => 0,
    }).collect()
}

fn make_f64() -> Vec<f64> {
    let mut s = Split(SEED);
    (0..N).map(|_| (s.next() % 100_000_000) as f64 / 7.0).collect()
}

fn wrapping_sum(v: &[i64]) -> u64 { v.iter().fold(0u64, |a, &x| a.wrapping_add(x as u64)) }

fn emit(run_id: &str, ts: &str, bench: &str, variant: &str, lib: &str,
        warmup: usize, trials: usize, mut s: Vec<u128>, check_ok: bool) {
    s.sort_unstable();
    let n = s.len();
    let sum: u128 = s.iter().sum();
    let (mn, med, mean, p95) = (s[0], s[n / 2], sum / n as u128, s[(n * 95 / 100).min(n - 1)]);
    let mels = if med > 0 { N as f64 / med as f64 * 1e9 / 1e6 } else { 0.0 };
    let status = if check_ok { "ok" } else { "invalid" };
    println!(
        "1,{run_id},{ts},{bench},sort,,{N},,{N},rust,{ver},{lib},std,-O3 lto target-cpu=native,{warmup},{trials},\
{mn},{med},{mean},{p95},{mels:.2},Melem/s,{rss},-1,{alloc},-1,-1,{status},{check},,{variant}",
        run_id = run_id, ts = ts, bench = bench, N = N, ver = env("PROFILE_LANG_VERSION", ""),
        lib = lib, warmup = warmup, trials = trials, mn = mn, med = med, mean = mean, p95 = p95,
        mels = mels, rss = peak_rss_kb(), alloc = _la(), status = status, check = check_ok, variant = variant);
}

fn bench_i64<F: Fn(&mut [i64])>(input: &[i64], warmup: usize, trials: usize, f: F)
    -> (Vec<u128>, bool) {
    let want = wrapping_sum(input);
    for _ in 0..warmup { let mut w = input.to_vec(); f(&mut w); }
    let mut samples = Vec::with_capacity(trials);
    let mut ok = true;
    for _ in 0..trials {
        let mut w = input.to_vec();
        let t = Instant::now();
        f(&mut w);
        samples.push(t.elapsed().as_nanos());
        ok = w.windows(2).all(|p| p[0] <= p[1]) && wrapping_sum(&w) == want;
    }
    _alloc_of(|| { let mut w = input.to_vec(); f(&mut w); });
    (samples, ok)
}

fn bench_f64<F: Fn(&mut [f64])>(input: &[f64], warmup: usize, trials: usize, f: F)
    -> (Vec<u128>, bool) {
    for _ in 0..warmup { let mut w = input.to_vec(); f(&mut w); }
    let mut samples = Vec::with_capacity(trials);
    let mut ok = true;
    for _ in 0..trials {
        let mut w = input.to_vec();
        let t = Instant::now();
        f(&mut w);
        samples.push(t.elapsed().as_nanos());
        ok = w.windows(2).all(|p| p[0] <= p[1]);
    }
    _alloc_of(|| { let mut w = input.to_vec(); f(&mut w); });
    (samples, ok)
}

fn main() {
    let run_id = env("PROFILE_RUN_ID", "local");
    let ts = env("PROFILE_RUN_TS", "");
    let warmup: usize = env("PROFILE_WARMUP", "3").parse().unwrap_or(3);
    let trials: usize = env("PROFILE_TRIALS", "10").parse().unwrap_or(10);

    // sort-int64: the unstable sort across all four patterns
    for variant in ["random", "ascending", "descending", "dups"] {
        let input = make_i64(variant);
        let (s, ok) = bench_i64(&input, warmup, trials, |w| w.sort_unstable());
        emit(&run_id, &ts, "sort-int64", variant, "std-unstable", warmup, trials, s, ok);
    }
    // sort-stable-int64: the stable sort (random only)
    {
        let input = make_i64("random");
        let (s, ok) = bench_i64(&input, warmup, trials, |w| w.sort());
        emit(&run_id, &ts, "sort-stable-int64", "", "std-stable", warmup, trials, s, ok);
    }
    // sort-f64: random
    {
        let input = make_f64();
        let (s, ok) = bench_f64(&input, warmup, trials, |w| w.sort_unstable_by(|a, b| a.total_cmp(b)));
        emit(&run_id, &ts, "sort-f64", "", "std-unstable", warmup, trials, s, ok);
    }
}
