// cajeta.lang String normalization + the Unicode Character Database
// (stdlib-completion U7; spec §7, §8.4). The FULL UCD ships compiled in
// (cajeta_rt_ucd_tables.h, generated by tools/ucd/gen_ucd_tables.py from
// pinned Unicode 16.0.0 data) so normalization is identical on every
// platform — the compare-equal property (§7.2) depends on that.
//
// Layout notes: tables are two-stage tries (128-wide deduped blocks);
// decompositions are pre-expanded at GENERATION time, so runtime
// decomposition is one lookup + Hangul arithmetic, never recursive.
// Canonical composition is a binary search over (starter<<21|combining)
// pairs. Hangul is fully algorithmic (UAX #15 §3.12) and appears in no
// table.
//
// String-level entry points mirror __cajeta_string_replace's convention:
// return NULL for "no change" so the .cajeta side hands back `this` —
// that is §7.4's already-normalized fast path, with no copy at all.
//
// This file is the PURE core: tables + codepoint algorithms + raw-buffer
// entry points, with no dependency on the String layout — so the Unicode
// conformance suite (test/ucd/) can compile the REAL implementation into
// the test binary directly. cajeta_rt_ucd.c layers the String wrappers on
// top; cajeta_runtime.c includes both.

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "cajeta_rt_ucd_tables.h"

#define CAJ_UCD_MAXCP 0x10FFFF

// Normalization form ids shared with cajeta.lang.String (§7.1):
//   0 = NFC, 1 = NFD, 2 = NFKC, 3 = NFKD.
enum { CAJ_NFC = 0, CAJ_NFD = 1, CAJ_NFKC = 2, CAJ_NFKD = 3 };

#define CAJ_UCD_LOOKUP(name, cp) \
    (caj_ucd_##name##_stage2[(uint32_t) caj_ucd_##name##_stage1[(cp) >> CAJ_UCD_BLOCK_SHIFT] \
        * (CAJ_UCD_BLOCK_MASK + 1) + ((cp) & CAJ_UCD_BLOCK_MASK)])

static inline uint32_t caj_ucd_ccc_of(uint32_t cp) {
    return cp <= CAJ_UCD_MAXCP ? CAJ_UCD_LOOKUP(ccc, cp) : 0;
}

// --- per-codepoint property surface (cajeta.lang.Ucd; text-shaping §13.2) --

int32_t __cajeta_ucd_ccc(int32_t cp) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0;
    return (int32_t) CAJ_UCD_LOOKUP(ccc, (uint32_t) cp);
}

int32_t __cajeta_ucd_script(int32_t cp) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0;
    return (int32_t) CAJ_UCD_LOOKUP(script, (uint32_t) cp);
}

int32_t __cajeta_ucd_joining_type(int32_t cp) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0;
    return (int32_t) CAJ_UCD_LOOKUP(join, (uint32_t) cp);
}

int32_t __cajeta_ucd_bidi_class(int32_t cp) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0;
    return (int32_t) CAJ_UCD_LOOKUP(bidi, (uint32_t) cp);
}

int32_t __cajeta_ucd_default_ignorable(int32_t cp) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0;
    return (int32_t) CAJ_UCD_LOOKUP(ign, (uint32_t) cp);
}

int32_t __cajeta_ucd_general_category(int32_t cp) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0; /* Cn */
    return (int32_t) CAJ_UCD_LOOKUP(gc, (uint32_t) cp);
}

int32_t __cajeta_ucd_white_space(int32_t cp) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0;
    return (int32_t) CAJ_UCD_LOOKUP(ws, (uint32_t) cp);
}

int32_t __cajeta_ucd_script_count(void) { return CAJ_UCD_SCRIPT_COUNT; }

const char* __cajeta_ucd_script_name(int32_t id) {
    if (id < 0 || id >= CAJ_UCD_SCRIPT_COUNT) return "Unknown";
    return caj_ucd_script_names[id];
}

const char* __cajeta_ucd_bidi_name(int32_t id) {
    if (id < 0 || id >= CAJ_UCD_BIDI_COUNT) return "L";
    return caj_ucd_bidi_names[id];
}

// --- UTF-8 <-> codepoints ---------------------------------------------------

// Strict decode of one scalar value. Returns byte length, or 0 on any
// malformation (overlong, surrogate, out of range, truncation) — the §7.1.7
// diagnostic contract rejects rather than replacing.
static int caj_ucd_decode(const uint8_t* s, int64_t i, int64_t n, uint32_t* out) {
    uint8_t b0 = s[i];
    if (b0 < 0x80) { *out = b0; return 1; }
    if (b0 < 0xC2) return 0;                       // continuation or overlong
    if (b0 < 0xE0) {
        if (i + 1 >= n || (s[i+1] & 0xC0) != 0x80) return 0;
        *out = ((uint32_t)(b0 & 0x1F) << 6) | (s[i+1] & 0x3F);
        return 2;
    }
    if (b0 < 0xF0) {
        if (i + 2 >= n || (s[i+1] & 0xC0) != 0x80 || (s[i+2] & 0xC0) != 0x80)
            return 0;
        uint32_t cp = ((uint32_t)(b0 & 0x0F) << 12)
                    | ((uint32_t)(s[i+1] & 0x3F) << 6) | (s[i+2] & 0x3F);
        if (cp < 0x800 || (cp >= 0xD800 && cp <= 0xDFFF)) return 0;
        *out = cp;
        return 3;
    }
    if (b0 < 0xF5) {
        if (i + 3 >= n || (s[i+1] & 0xC0) != 0x80 || (s[i+2] & 0xC0) != 0x80
                || (s[i+3] & 0xC0) != 0x80)
            return 0;
        uint32_t cp = ((uint32_t)(b0 & 0x07) << 18)
                    | ((uint32_t)(s[i+1] & 0x3F) << 12)
                    | ((uint32_t)(s[i+2] & 0x3F) << 6) | (s[i+3] & 0x3F);
        if (cp < 0x10000 || cp > 0x10FFFF) return 0;
        *out = cp;
        return 4;
    }
    return 0;
}

static int caj_ucd_encode(uint32_t cp, uint8_t* out) {
    if (cp < 0x80) { out[0] = (uint8_t) cp; return 1; }
    if (cp < 0x800) {
        out[0] = 0xC0 | (cp >> 6);
        out[1] = 0x80 | (cp & 0x3F);
        return 2;
    }
    if (cp < 0x10000) {
        out[0] = 0xE0 | (cp >> 12);
        out[1] = 0x80 | ((cp >> 6) & 0x3F);
        out[2] = 0x80 | (cp & 0x3F);
        return 3;
    }
    out[0] = 0xF0 | (cp >> 18);
    out[1] = 0x80 | ((cp >> 12) & 0x3F);
    out[2] = 0x80 | ((cp >> 6) & 0x3F);
    out[3] = 0x80 | (cp & 0x3F);
    return 4;
}

// Whole-buffer strict validity (the .cajeta side throws EncodingException
// on 0 BEFORE normalizing — §7.1.7).
int32_t __cajeta_ucd_utf8_valid_buf(const uint8_t* p, int64_t n) {
    int64_t i = 0;
    uint32_t cp;
    while (i < n) {
        int len = caj_ucd_decode(p, i, n, &cp);
        if (len == 0) return 0;
        i += len;
    }
    return 1;
}

// --- codepoint-buffer normalization ----------------------------------------

typedef struct {
    uint32_t* cp;
    int64_t len;
    int64_t cap;
} caj_cpbuf;

static void caj_cpbuf_push(caj_cpbuf* b, uint32_t cp) {
    if (b->len == b->cap) {
        int64_t ncap = b->cap ? b->cap * 2 : 64;
        uint32_t* np = (uint32_t*) malloc((size_t) ncap * 4);
        memcpy(np, b->cp, (size_t) b->len * 4);
        free(b->cp);
        b->cp = np;
        b->cap = ncap;
    }
    b->cp[b->len++] = cp;
}

// Decompose one codepoint into `out` under `form` (canonical for NFC/NFD,
// compatibility for the K forms). Hangul is algorithmic.
static void caj_ucd_decompose_cp(uint32_t cp, int compat, caj_cpbuf* out) {
    // Hangul syllable -> L V (T)
    if (cp >= 0xAC00 && cp < 0xAC00 + 11172) {
        uint32_t sindex = cp - 0xAC00;
        caj_cpbuf_push(out, 0x1100 + sindex / (21 * 28));
        caj_cpbuf_push(out, 0x1161 + (sindex % (21 * 28)) / 28);
        uint32_t t = sindex % 28;
        if (t) caj_cpbuf_push(out, 0x11A7 + t);
        return;
    }
    if (cp <= CAJ_UCD_MAXCP) {
        uint32_t idx = 0;
        if (compat) {
            idx = CAJ_UCD_LOOKUP(compat, cp);
            if (!idx) idx = CAJ_UCD_LOOKUP(canon, cp);
        } else {
            idx = CAJ_UCD_LOOKUP(canon, cp);
        }
        if (idx) {
            uint32_t n = caj_ucd_pool[idx];
            for (uint32_t k = 1; k <= n; k++)
                caj_cpbuf_push(out, caj_ucd_pool[idx + k]);
            return;
        }
    }
    caj_cpbuf_push(out, cp);
}

// Canonical ordering: stable-sort runs of nonzero-ccc marks (UAX #15).
static void caj_ucd_order(caj_cpbuf* b) {
    for (int64_t i = 1; i < b->len; i++) {
        uint32_t c = caj_ucd_ccc_of(b->cp[i]);
        if (!c) continue;
        int64_t j = i;
        while (j > 0) {
            uint32_t prev = caj_ucd_ccc_of(b->cp[j - 1]);
            if (prev == 0 || prev <= c) break;
            uint32_t t = b->cp[j];
            b->cp[j] = b->cp[j - 1];
            b->cp[j - 1] = t;
            j--;
        }
    }
}

static uint32_t caj_ucd_pair_lookup(uint32_t a, uint32_t b) {
    uint64_t key = ((uint64_t) a << 21) | b;
    int64_t lo = 0, hi = CAJ_UCD_PAIR_COUNT - 1;
    while (lo <= hi) {
        int64_t mid = (lo + hi) >> 1;
        uint64_t k = caj_ucd_pair_keys[mid];
        if (k == key) return caj_ucd_pair_vals[mid];
        if (k < key) lo = mid + 1;
        else hi = mid - 1;
    }
    return 0;
}

// Canonical composition in place (UAX #15 §3.11), including Hangul LV/LVT.
static void caj_ucd_compose(caj_cpbuf* b) {
    if (b->len == 0) return;
    int64_t starter = -1;
    uint32_t starter_ccc_seen = 0;   // highest ccc seen since the starter
    int64_t w = 0;
    for (int64_t i = 0; i < b->len; i++) {
        uint32_t cp = b->cp[i];
        uint32_t ccc = caj_ucd_ccc_of(cp);
        if (starter >= 0) {
            uint32_t s = b->cp[starter];
            // not blocked: immediately follows the starter, or the last
            // combining char has strictly lower ccc
            if ((int64_t) w == starter + 1 || starter_ccc_seen < ccc) {
                uint32_t comp = 0;
                // Hangul L+V and LV+T
                if (s >= 0x1100 && s < 0x1100 + 19 && cp >= 0x1161
                        && cp < 0x1161 + 21) {
                    comp = 0xAC00 + ((s - 0x1100) * 21 + (cp - 0x1161)) * 28;
                } else if (s >= 0xAC00 && s < 0xAC00 + 11172
                        && ((s - 0xAC00) % 28) == 0 && cp > 0x11A7
                        && cp < 0x11A7 + 28) {
                    comp = s + (cp - 0x11A7);
                } else {
                    comp = caj_ucd_pair_lookup(s, cp);
                }
                if (comp) {
                    b->cp[starter] = comp;
                    continue;                        // cp consumed
                }
            }
        }
        if (ccc == 0) {
            starter = w;
            starter_ccc_seen = 0;
        } else if (ccc > starter_ccc_seen) {
            starter_ccc_seen = ccc;
        }
        b->cp[w++] = cp;
    }
    b->len = w;
}

// --- raw-buffer entry points (shared by the String wrappers and the
// conformance suite) -------------------------------------------------------

// Quick-check scan: 1 = definitely in `form`, 0 = No/Maybe/misordered or
// malformed (callers that transform validate first and throw).
int32_t __cajeta_ucd_is_normalized_buf(const uint8_t* p, int64_t n,
                                       int32_t form) {
    static const int shift[4] = { 2 /*NFC*/, 0 /*NFD*/, 6 /*NFKC*/, 4 /*NFKD*/ };
    int sh = shift[form & 3];
    int64_t i = 0;
    uint32_t prev_ccc = 0;
    uint32_t cp;
    while (i < n) {
        int len = caj_ucd_decode(p, i, n, &cp);
        if (len == 0) return 0;
        uint32_t ccc = caj_ucd_ccc_of(cp);
        if (ccc && ccc < prev_ccc) return 0;         // misordered marks
        if (cp <= CAJ_UCD_MAXCP && ((CAJ_UCD_LOOKUP(qc, cp) >> sh) & 3))
            return 0;                                 // QC No or Maybe
        prev_ccc = ccc;
        i += len;
    }
    return 1;
}

// Normalize `p[0..n)` into `form`. On success returns the byte length and
// stores a malloc'd buffer in *out (caller frees). Returns -1 on malformed
// input.
int64_t __cajeta_ucd_normalize_buf(const uint8_t* p, int64_t n, int32_t form,
                                   uint8_t** out) {
    int compat = (form == CAJ_NFKC || form == CAJ_NFKD);
    int compose = (form == CAJ_NFC || form == CAJ_NFKC);
    caj_cpbuf b = { 0, 0, 0 };
    int64_t i = 0;
    uint32_t cp;
    while (i < n) {
        int len = caj_ucd_decode(p, i, n, &cp);
        if (len == 0) { free(b.cp); return -1; }
        caj_ucd_decompose_cp(cp, compat, &b);
        i += len;
    }
    caj_ucd_order(&b);
    if (compose) caj_ucd_compose(&b);
    uint8_t* bytes = (uint8_t*) malloc((size_t) (b.len * 4 + 1));
    int64_t w = 0;
    for (int64_t k = 0; k < b.len; k++)
        w += caj_ucd_encode(b.cp[k], bytes + w);
    free(b.cp);
    *out = bytes;
    return w;
}

// Full case folding of one codepoint into out[0..2]; returns the count,
// 0 = identity.
int32_t __cajeta_ucd_fold_cp(int32_t cp, uint32_t* out) {
    if (cp < 0 || cp > CAJ_UCD_MAXCP) return 0;
    uint32_t idx = CAJ_UCD_LOOKUP(fold, (uint32_t) cp);
    if (!idx) return 0;
    uint32_t n = caj_ucd_pool[idx];
    for (uint32_t k = 1; k <= n && k <= 3; k++) out[k - 1] = caj_ucd_pool[idx + k];
    return (int32_t) n;
}

// Strict single-codepoint decode/encode, exported for the wrappers.
int32_t __cajeta_ucd_decode_cp(const uint8_t* p, int64_t i, int64_t n,
                               uint32_t* out) {
    return caj_ucd_decode(p, i, n, out);
}

int32_t __cajeta_ucd_encode_cp(uint32_t cp, uint8_t* out) {
    return caj_ucd_encode(cp, out);
}
