// `cajeta stdlib <list|extract <dir>>` — stdlib source access
// (ide-symbol-index §6.0.3).
//
// The stdlib `.cajeta` sources are embedded in the compiler binary
// (cajeta::stdlib::g_files, generated by cmake/EmbedStdlib.cmake). This is
// the way out: the IDE plugin extracts them to a cache directory, mounts and
// indexes them, so navigation and debug stops in stdlib frames land in real
// files. `list` reports the embedded set (one relative path per line on
// stdout) without writing anything; `extract <dir>` writes the tree under
// <dir> preserving package paths, plus a `.cajeta-stdlib.json` identity
// marker (compiler version + git hash + file count) the plugin keys its
// cache on.

#pragma once

namespace cajeta {

    // Dispatch `cajeta stdlib <verb> [args...]`. argc/argv are passed
    // unchanged from main; the verb is at argv[2]. Returns the process
    // exit code.
    int dispatchStdlib(int argc, const char* argv[]);

} // namespace cajeta
