//
// Shared Cajeta source for the Stage-12 proof-of-support compute probes, so the
// SAME program runs on every backend (CPU oracle + on-device Vulkan/AMD) — the
// plan's "on-device gates ride the same sources". Each is a complete program
// whose run() self-checks and returns 777. Buffers use the explicit
// allocate()/free() idiom, which is correct on every backend (device backends
// need the explicit device allocation; CPU honors it too).
//
// Consumed by XpuComputeProbeTests.cpp (CPU) and XpuComputeProbeDeviceTests.cpp
// (Vulkan). See those for the per-target rationale.
//
#pragma once

namespace cajeta_test_probes {

// Target 1: numerics — broadcast-shaped element-wise (per-row scale/bias) + an
// atomic-sum reduction. y[r*cols+c] = x[r*cols+c]*scale[r] + bias[r]; acc[0] =
// sum(y). Exercises multiple buffers, broadcast indexing, float atomics, FFI.
inline const char* kNumericsBroadcastReduce() {
    return
    "package test;\n"
    "import cajeta.xpu.KernelBuffer;\n"
    "import cajeta.xpu.KernelStream;\n"
    "import cajeta.xpu.KernelThread;\n"
    "public class NumProbe {\n"
    "    @Kernel\n"
    "    public static void broadcastReduce(KernelBuffer<float32> acc,\n"
    "                                       KernelBuffer<float32> y, KernelBuffer<float32> x,\n"
    "                                       KernelBuffer<float32> scale,\n"
    "                                       KernelBuffer<float32> bias,\n"
    "                                       uint32 cols, uint32 n) {\n"
    "        uint32 i = KernelThread.globalIdX();\n"
    "        if (i < n) {\n"
    "            uint32 r = i / cols;\n"
    "            float32 v = x[i] * scale[r] + bias[r];\n"
    "            y[i] = v;\n"
    "            acc.atomicAdd(0, v);\n"
    "        }\n"
    "    }\n"
    "    public static int32 run() {\n"
    "        uint32 rows = 8;\n"
    "        uint32 cols = 64;\n"
    "        uint32 n = rows * cols;\n"
    "        float32[] hx = heap float32[n];\n"
    "        float32[] hsc = heap float32[rows];\n"
    "        float32[] hbi = heap float32[rows];\n"
    "        for (uint32 r = 0; r < rows; r = r + 1) {\n"
    "            hsc[r] = (float32)(r) + 1.0f;\n"
    "            hbi[r] = (float32)(r) * 0.5f;\n"
    "            for (uint32 c = 0; c < cols; c = c + 1) {\n"
    "                hx[r * cols + c] = (float32)(c);\n"
    "            }\n"
    "        }\n"
    "        float32[] hy = heap float32[n];\n"
    "        for (uint32 i = 0; i < n; i = i + 1) { hy[i] = -1.0f; }\n"
    "        float32[] hacc = heap float32[1];\n"
    "        hacc[0] = 0.0f;\n"
    "        KernelBuffer<float32> x = heap KernelBuffer<float32>(0, n);\n"
    "        KernelBuffer<float32> sc = heap KernelBuffer<float32>(0, rows);\n"
    "        KernelBuffer<float32> bi = heap KernelBuffer<float32>(0, rows);\n"
    "        KernelBuffer<float32> y = heap KernelBuffer<float32>(0, n);\n"
    "        KernelBuffer<float32> acc = heap KernelBuffer<float32>(0, 1);\n"
    "        x.allocate(); sc.allocate(); bi.allocate();\n"
    "        y.allocate(); acc.allocate();\n"
    "        x.upload(hx); sc.upload(hsc); bi.upload(hbi);\n"
    "        y.upload(hy); acc.upload(hacc);\n"
    "        KernelStream s = KernelStream.current();\n"
    "        broadcastReduce.launch(s, grid: [(n + 63) / 64], block: [64])"
            "(acc, y, x, sc, bi, cols, n);\n"
    "        s.sync();\n"
    "        y.download(hy);\n"
    "        acc.download(hacc);\n"
    "        x.free(); sc.free(); bi.free(); y.free(); acc.free();\n"
    "        float32 expSum = 0.0f;\n"
    "        for (uint32 r = 0; r < rows; r = r + 1) {\n"
    "            for (uint32 c = 0; c < cols; c = c + 1) {\n"
    "                float32 e = (float32)(c) * hsc[r] + hbi[r];\n"
    "                float32 dy = hy[r * cols + c] - e;\n"
    "                if (dy < -0.001f || dy > 0.001f) {\n"
    "                    return (int32)(100 + r * cols + c);\n"
    "                }\n"
    "                expSum = expSum + e;\n"
    "            }\n"
    "        }\n"
    "        float32 d = hacc[0] - expSum;\n"
    "        if (d < -1.0f || d > 1.0f) { return 2; }\n"
    "        return 777;\n"
    "    }\n"
    "}\n";
}

// Target 2: PyTorch — matmul (accumulate over K) + atomic scatter-add with
// colliding indices (grad accumulation). Both verified vs a CPU recomputation.
inline const char* kTorchMatmulScatter() {
    return
    "package test;\n"
    "import cajeta.xpu.KernelBuffer;\n"
    "import cajeta.xpu.KernelStream;\n"
    "import cajeta.xpu.KernelThread;\n"
    "public class TorchProbe {\n"
    "    @Kernel\n"
    "    public static void matmul(KernelBuffer<float32> C, KernelBuffer<float32> A,\n"
    "                              KernelBuffer<float32> B, uint32 M, uint32 K,\n"
    "                              uint32 N) {\n"
    "        uint32 i = KernelThread.globalIdX();\n"
    "        if (i < M * N) {\n"
    "            uint32 row = i / N;\n"
    "            uint32 col = i - row * N;\n"
    "            float32 acc = 0.0f;\n"
    "            for (uint32 k = 0; k < K; k = k + 1) {\n"
    "                acc = acc + A[row * K + k] * B[k * N + col];\n"
    "            }\n"
    "            C[i] = acc;\n"
    "        }\n"
    "    }\n"
    "    @Kernel\n"
    "    public static void scatterAdd(KernelBuffer<float32> grad, KernelBuffer<int32> idx,\n"
    "                                  KernelBuffer<float32> val, uint32 n) {\n"
    "        uint32 i = KernelThread.globalIdX();\n"
    "        if (i < n) {\n"
    "            grad.atomicAdd(idx[i], val[i]);\n"
    "        }\n"
    "    }\n"
    "    public static int32 run() {\n"
    "        uint32 M = 8; uint32 K = 16; uint32 N = 8;\n"
    "        uint32 nA = M * K; uint32 nB = K * N; uint32 nC = M * N;\n"
    "        float32[] hA = heap float32[nA];\n"
    "        float32[] hB = heap float32[nB];\n"
    "        for (uint32 m = 0; m < M; m = m + 1) {\n"
    "            for (uint32 k = 0; k < K; k = k + 1) {\n"
    "                hA[m * K + k] = (float32)(m + k);\n"
    "            }\n"
    "        }\n"
    "        for (uint32 k = 0; k < K; k = k + 1) {\n"
    "            for (uint32 nn = 0; nn < N; nn = nn + 1) {\n"
    "                hB[k * N + nn] = (float32)(k + nn);\n"
    "            }\n"
    "        }\n"
    "        float32[] hC = heap float32[nC];\n"
    "        for (uint32 i = 0; i < nC; i = i + 1) { hC[i] = -1.0f; }\n"
    "        KernelBuffer<float32> A = heap KernelBuffer<float32>(0, nA);\n"
    "        KernelBuffer<float32> B = heap KernelBuffer<float32>(0, nB);\n"
    "        KernelBuffer<float32> C = heap KernelBuffer<float32>(0, nC);\n"
    "        A.allocate(); B.allocate(); C.allocate();\n"
    "        A.upload(hA); B.upload(hB); C.upload(hC);\n"
    "        KernelStream s = KernelStream.current();\n"
    "        matmul.launch(s, grid: [(nC + 63) / 64], block: [64])"
            "(C, A, B, M, K, N);\n"
    "        s.sync();\n"
    "        C.download(hC);\n"
    "        A.free(); B.free(); C.free();\n"
    "        for (uint32 m = 0; m < M; m = m + 1) {\n"
    "            for (uint32 nn = 0; nn < N; nn = nn + 1) {\n"
    "                float32 e = 0.0f;\n"
    "                for (uint32 k = 0; k < K; k = k + 1) {\n"
    "                    e = e + hA[m * K + k] * hB[k * N + nn];\n"
    "                }\n"
    "                float32 d = hC[m * N + nn] - e;\n"
    "                if (d < -0.01f || d > 0.01f) {\n"
    "                    return (int32)(100 + m * N + nn);\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        uint32 ns = 256; uint32 P = 8;\n"
    "        int32[] hidx = heap int32[ns];\n"
    "        float32[] hval = heap float32[ns];\n"
    "        for (uint32 i = 0; i < ns; i = i + 1) {\n"
    "            hidx[i] = (int32)(i % P);\n"
    "            hval[i] = (float32)(i % 4) * 0.25f;\n"
    "        }\n"
    "        float32[] hg = heap float32[P];\n"
    "        for (uint32 b = 0; b < P; b = b + 1) { hg[b] = 0.0f; }\n"
    "        KernelBuffer<int32> idx = heap KernelBuffer<int32>(0, ns);\n"
    "        KernelBuffer<float32> val = heap KernelBuffer<float32>(0, ns);\n"
    "        KernelBuffer<float32> grad = heap KernelBuffer<float32>(0, P);\n"
    "        idx.allocate(); val.allocate(); grad.allocate();\n"
    "        idx.upload(hidx); val.upload(hval); grad.upload(hg);\n"
    "        scatterAdd.launch(s, grid: [(ns + 63) / 64], block: [64])"
            "(grad, idx, val, ns);\n"
    "        s.sync();\n"
    "        grad.download(hg);\n"
    "        idx.free(); val.free(); grad.free();\n"
    "        float32[] eg = heap float32[P];\n"
    "        for (uint32 b = 0; b < P; b = b + 1) { eg[b] = 0.0f; }\n"
    "        for (uint32 i = 0; i < ns; i = i + 1) {\n"
    "            eg[i % P] = eg[i % P] + (float32)(i % 4) * 0.25f;\n"
    "        }\n"
    "        for (uint32 b = 0; b < P; b = b + 1) {\n"
    "            float32 d = hg[b] - eg[b];\n"
    "            if (d < -0.01f || d > 0.01f) { return (int32)(200 + b); }\n"
    "        }\n"
    "        return 777;\n"
    "    }\n"
    "}\n";
}

// Target 3: Caramelo/SPELA — fused forward + local-loss + per-neuron weight update
// in ONE device pass (no atomics; one thread per output neuron owns its W row).
inline const char* kSpelaFusedLayer() {
    return
    "package test;\n"
    "import cajeta.xpu.KernelBuffer;\n"
    "import cajeta.xpu.KernelStream;\n"
    "import cajeta.xpu.KernelThread;\n"
    "public class SpelaProbe {\n"
    "    @Kernel\n"
    "    public static void fusedLayer(KernelBuffer<float32> W, KernelBuffer<float32> x,\n"
    "                                  KernelBuffer<float32> t, KernelBuffer<float32> loss,\n"
    "                                  uint32 inDim, uint32 outDim, float32 lr) {\n"
    "        uint32 j = KernelThread.globalIdX();\n"
    "        if (j < outDim) {\n"
    "            float32 a = 0.0f;\n"
    "            for (uint32 i = 0; i < inDim; i = i + 1) {\n"
    "                a = a + W[j * inDim + i] * x[i];\n"
    "            }\n"
    "            float32 err = t[j] - a;\n"
    "            loss[j] = err * err;\n"
    "            for (uint32 i = 0; i < inDim; i = i + 1) {\n"
    "                W[j * inDim + i] = W[j * inDim + i] + lr * err * x[i];\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    public static int32 run() {\n"
    "        uint32 inDim = 16; uint32 outDim = 8;\n"
    "        float32 lr = 0.1f;\n"
    "        uint32 nW = inDim * outDim;\n"
    "        float32[] hW = heap float32[nW];\n"
    "        float32[] hx = heap float32[inDim];\n"
    "        float32[] ht = heap float32[outDim];\n"
    "        for (uint32 j = 0; j < outDim; j = j + 1) {\n"
    "            for (uint32 i = 0; i < inDim; i = i + 1) {\n"
    "                hW[j * inDim + i] = 0.01f * (float32)((j + i) % 5);\n"
    "            }\n"
    "        }\n"
    "        for (uint32 i = 0; i < inDim; i = i + 1) {\n"
    "            hx[i] = 0.5f * (float32)(i % 3);\n"
    "        }\n"
    "        for (uint32 j = 0; j < outDim; j = j + 1) {\n"
    "            ht[j] = 0.25f * (float32)(j % 4);\n"
    "        }\n"
    "        float32[] hloss = heap float32[outDim];\n"
    "        for (uint32 j = 0; j < outDim; j = j + 1) { hloss[j] = -1.0f; }\n"
    "        KernelBuffer<float32> W = heap KernelBuffer<float32>(0, nW);\n"
    "        KernelBuffer<float32> x = heap KernelBuffer<float32>(0, inDim);\n"
    "        KernelBuffer<float32> t = heap KernelBuffer<float32>(0, outDim);\n"
    "        KernelBuffer<float32> loss = heap KernelBuffer<float32>(0, outDim);\n"
    "        W.allocate(); x.allocate(); t.allocate(); loss.allocate();\n"
    "        W.upload(hW); x.upload(hx); t.upload(ht); loss.upload(hloss);\n"
    "        KernelStream s = KernelStream.current();\n"
    "        fusedLayer.launch(s, grid: [1], block: [outDim])"
            "(W, x, t, loss, inDim, outDim, lr);\n"
    "        s.sync();\n"
    "        W.download(hW);\n"
    "        loss.download(hloss);\n"
    "        W.free(); x.free(); t.free(); loss.free();\n"
    "        for (uint32 j = 0; j < outDim; j = j + 1) {\n"
    "            float32 a = 0.0f;\n"
    "            for (uint32 i = 0; i < inDim; i = i + 1) {\n"
    "                a = a + 0.01f * (float32)((j + i) % 5) * hx[i];\n"
    "            }\n"
    "            float32 err = ht[j] - a;\n"
    "            float32 dl = hloss[j] - err * err;\n"
    "            if (dl < -0.001f || dl > 0.001f) { return (int32)(100 + j); }\n"
    "            for (uint32 i = 0; i < inDim; i = i + 1) {\n"
    "                float32 ew = 0.01f * (float32)((j + i) % 5) + lr * err * hx[i];\n"
    "                float32 dw = hW[j * inDim + i] - ew;\n"
    "                if (dw < -0.001f || dw > 0.001f) {\n"
    "                    return (int32)(200 + j * inDim + i);\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        return 777;\n"
    "    }\n"
    "}\n";
}

}  // namespace cajeta_test_probes
