package dev.cajeta.idea.profiler

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * cajeta-profiler 11.1.d — host, fiber, and device tracks on ONE axis
 * (spec §8.3), from a GENUINE run.
 *
 * `amdgpu.pftrace` is an env-armed, shutdown-drained profile of a program
 * whose fibers do CPU work and launch kernels on their own streams, captured
 * on real hardware through rocprofiler dispatch records — nothing in it is
 * synthetic (regenerated by `ProfilerGpuFixtureTests.writeAmdgpuFiberTrace`).
 * The other two fixtures each miss a lane: `tour.pftrace` has fibers and no
 * GPU work, `gpu.pftrace` has device tiers and no fibers. Only a trace
 * carrying all three can say the three lanes actually meet on one timeline —
 * which is the §8.3 claim, and a property of the MODEL, not of a renderer.
 */
class RealAmdgpuTraceTest {

    private fun model(): ProfileViewModel {
        val url = javaClass.classLoader.getResource("profiler/amdgpu.pftrace")
        assertNotNull("fixture profiler/amdgpu.pftrace is missing", url)
        return ProfileViewModel.of(PerfettoTraceReader.read(File(url!!.toURI()).readBytes()))
    }

    @Test
    fun allThreeLaneKindsArePresentAndCarryWork() {
        val m = model()
        val kinds = m.tracks.groupBy { it.kind }
        assertTrue("no host thread track", TrackKind.THREAD in kinds)
        assertTrue("no fiber track — the workers were not sampled as fibers",
            TrackKind.FIBER in kinds)
        assertTrue("no device queue track", TrackKind.DEVICE_QUEUE in kinds)
        assertTrue("no device structure track", TrackKind.DEVICE in kinds)

        // Presence alone would pass on empty lanes. Each kind of lane must
        // hold actual frames from this run.
        assertTrue("fiber tracks are empty",
            kinds.getValue(TrackKind.FIBER).any { it.roots.isNotEmpty() })
        assertTrue("device queues are empty",
            kinds.getValue(TrackKind.DEVICE_QUEUE).any { it.roots.isNotEmpty() })
        assertTrue("host thread tracks are empty",
            kinds.getValue(TrackKind.THREAD).any { it.roots.isNotEmpty() })
    }

    @Test
    fun everyWorkLaneSitsInsideTheOneAxis() {
        val m = model()
        assertTrue("the axis has no extent", m.spanNs > 0)
        for (t in m.workTracks.filter { it.startNs > 0 }) {
            assertTrue("${t.name} starts before the shared axis", t.startNs >= m.startNs)
            assertTrue("${t.name} ends after the shared axis", t.endNs <= m.endNs)
        }
        // The three kinds genuinely overlap in time — fibers were running
        // while their kernels executed. Three lanes that merely abut on one
        // axis would render fine and say nothing about concurrency.
        val fiber = m.workTracks.first { it.kind == TrackKind.FIBER }
        val queue = m.workTracks.first { it.kind == TrackKind.DEVICE_QUEUE }
        assertTrue("the fiber and its device queue never overlap in time",
            fiber.startNs < queue.endNs && queue.startNs < fiber.endNs)
    }

    @Test
    fun deviceFramesLayOutAgainstTheSharedAxisNotTheirOwn() {
        val m = model()
        for (queue in m.tracks.filter { it.kind == TrackKind.DEVICE_QUEUE }) {
            val (rects, _) = FlameLayout.of(m, queue, minWidth = 0.0)
            assertTrue("queue ${queue.name} laid out no frames", rects.isNotEmpty())
            for (r in rects) {
                assertTrue("${r.node.name} starts before the axis", r.x >= 0.0)
                assertTrue("${r.node.name} runs past the axis",
                    r.x + r.width <= 1.0 + 1e-9)
            }
            // A kernel burst is a sliver of this run, not a full-width bar.
            val covered = rects.filter { it.depth == 0 }.sumOf { it.width }
            assertTrue("queue ${queue.name} covers the whole axis ($covered)",
                covered < 1.0)
        }
    }

    @Test
    fun queuesIndentUnderTheirDeviceInTheTimeline() {
        val rows = TrackHierarchy.flatten(model().tracks)
        val queues = rows.filter { it.view.kind == TrackKind.DEVICE_QUEUE }
        assertEquals("the run launched on two streams", 2, queues.size)
        assertTrue("queues drawn at top level, not under their device",
            queues.all { it.depth > 0 })
    }

    @Test
    fun theDeviceSpansAreGenuineDeviceMeasurements() {
        // The whole point of vendoring a real trace: these tiers were not
        // republished copies. Every span on a queue came from a rocprofiler
        // dispatch record and passed the runtime's integrity check (plan 6.7).
        val m = model()
        val queues = m.tracks.filter { it.kind == TrackKind.DEVICE_QUEUE }
        var spans = 0
        for (q in queues) {
            for (root in q.roots) {
                val quality = m.qualityOf(root)
                assertNotNull("a device span with no measurement quality", quality)
                assertEquals(ProfileTier.DEVICE, quality!!.tier)
                assertTrue("a genuine device span arrived flagged: ${quality.reasons}",
                    !quality.flagged)
                spans++
            }
        }
        assertEquals("the run made 16 launches", 16, spans)
    }
}
