package dev.cajeta.idea.buildtool

import dev.cajeta.idea.debugger.Json
import dev.cajeta.idea.lint.Diagnostic

/**
 * One compiler diagnostic parsed from the `--diag-format=json` NDJSON stream
 * (json-diagnostics-spec §3). `code`/`file`/`line`/`column` are null when the
 * compiler emitted JSON null (or omitted them); `line`/`column` are 1-based as
 * emitted (`Diagnostics.h::emitJsonDiagnostic`). Severity uses the single
 * degraded-lint vocabulary (`lint/Diagnostic.Severity`).
 */
data class JsonDiagnostic(
    val severity: Diagnostic.Severity,
    val code: String?,
    val message: String,
    val file: String?,
    val line: Int?,
    val column: Int?,
    val at: String? = null,
    val via: String? = null,
    val from: JsonLocation? = null,
    val archive: String? = null,
    val artifact: JsonArtifact? = null,
) {
    /** The message with what produced it: the generator for generated code, the subject for an artifact. */
    val displayMessage: String
        get() = when {
            via != null -> message + " (in code generated by " + via +
                (from?.let { if (it.line != null) " from ${it.file}:${it.line}" else "" } ?: "") + ")"
            artifact != null -> message + " (" + artifact.kind + " " + artifact.name +
                (artifact.target?.let { " on $it" } ?: "") + ")"
            else -> message
        }
}

/** A source position a 1.2 diagnostic names beside its own location. */
data class JsonLocation(val file: String, val line: Int?, val column: Int?)

/** The non-source subject of a 1.2 diagnostic: a kernel, a manifest key path, or a build step. */
data class JsonArtifact(val kind: String, val name: String, val target: String?)

/**
 * Parses one NDJSON diagnostic line, reusing the bundled dependency-free [Json]
 * DOM (which decodes RFC-8259 escapes). Returns null for a line that is not a
 * JSON diagnostic object — a non-diagnostic console line, malformed JSON, or a
 * JSON object without a recognized `severity` — so the caller leaves it as plain
 * console output (no regex fallback; json-diagnostics-spec §1.4.4). Pure.
 */
object JsonDiagnosticParser {

    fun parse(line: String): JsonDiagnostic? {
        val trimmed = line.trim()
        if (trimmed.isEmpty() || trimmed[0] != '{') return null
        val root = try {
            Json.parse(trimmed)
        } catch (_: Exception) {
            return null
        }
        if (root !is Json.Obj) return null
        val severity = severityOf((root.opt("severity") as? Json.Str)?.value) ?: return null
        return JsonDiagnostic(
            severity = severity,
            code = (root.opt("code") as? Json.Str)?.value,
            message = (root.opt("message") as? Json.Str)?.value ?: "",
            file = (root.opt("file") as? Json.Str)?.value,
            line = (root.opt("line") as? Json.Num)?.value?.toInt(),
            column = (root.opt("column") as? Json.Num)?.value?.toInt(),
            at = (root.opt("at") as? Json.Str)?.value,
            via = (root.opt("via") as? Json.Str)?.value,
            from = locationOf(root.opt("from")),
            archive = (root.opt("archive") as? Json.Str)?.value,
            artifact = artifactOf(root.opt("artifact")),
        )
    }

    private fun locationOf(v: Json?): JsonLocation? {
        val o = v as? Json.Obj ?: return null
        val file = (o.opt("file") as? Json.Str)?.value ?: return null
        return JsonLocation(file, (o.opt("line") as? Json.Num)?.value?.toInt(),
            (o.opt("column") as? Json.Num)?.value?.toInt())
    }

    private fun artifactOf(v: Json?): JsonArtifact? {
        val o = v as? Json.Obj ?: return null
        val kind = (o.opt("kind") as? Json.Str)?.value ?: return null
        val name = (o.opt("name") as? Json.Str)?.value ?: return null
        return JsonArtifact(kind, name, (o.opt("target") as? Json.Str)?.value)
    }

    private fun severityOf(s: String?): Diagnostic.Severity? = when (s) {
        "error" -> Diagnostic.Severity.ERROR
        "warning" -> Diagnostic.Severity.WARNING
        "note" -> Diagnostic.Severity.WEAK_WARNING
        else -> null
    }
}
