#!/usr/bin/env python3
"""
report_owned_binds.py — turn a warn-mode harvest into the 8.2.7 worklist.

stdlib-ownership-convention plan, 8.2.7 (spec §4.6): a `#T` result must be
received with `#=`. Input is the compiler's own notes from

    CAJETA_OWNED_BIND=warn CAJETA_AUDIT_RETURN_TITLES=1 cajeta build 2> log

which emit

    cajeta: note: [owned-bind] <class>.<method>:<line> lvalue=<x> callee=<key>
    cajeta: note: [owned-bind] <class>.<method>:<line> callee=<key> pos=assign

The first is the DECLARATION position — what 8.2.7 rejects, and the population
the 148-site sizing covered. The second is the ASSIGNMENT position, counted but
NOT rejected: §4.6's wording covers it, the measurement did not, and shipping a
rule against an unmeasured population is what cost Unit 3 its gate (3.3.3).
They are reported separately so the second is a decision (8.2.12) rather than a
surprise.

Grouped by CALLEE, not by file, because that is where the leverage is: 38 of
the first 148 sites were `String.toBytes`, and a migration ordered by callee
lets one producer's whole fan-out be done and reviewed as a unit.

Usage: report_owned_binds.py <harvest.log> [more.log ...] > worklist.md
"""

import re
import sys
from collections import defaultdict

DECL_RE = re.compile(
    r'\[owned-bind\] (?P<inm>[^\s]+?):(?P<line>-?\d+) '
    r'lvalue=(?P<lvalue>\S+) callee=(?P<callee>\S+)')
ASSIGN_RE = re.compile(
    r'\[owned-bind\] (?P<inm>[^\s]+?):(?P<line>-?\d+) '
    r'callee=(?P<callee>\S+) pos=assign')
# The pre-check sizing shape (audit only, error mode) — still parsed so an old
# harvest can be re-reported without re-running it.
SIZING_RE = re.compile(
    r'\[owned-bind\] (?P<inm>[^\s]+?):(?P<line>-?\d+) '
    r'callee=(?P<callee>\S+)$')

GENERIC_RE = re.compile(r'<[^<>]*>')


def strip_generics(name):
    """`Optional<String>.get` -> `Optional.get`.

    One generic class instantiated five ways is ONE method to migrate.
    Counting instantiations inflated the 8.1.1 inventory before this existed.
    """
    prev = None
    while prev != name:
        prev = name
        name = GENERIC_RE.sub('', name)
    return name


def main(argv):
    if len(argv) < 2:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    seen_notes = [0]           # every [owned-bind] line, parsed or not
    unparsed = []              # note lines matching none of the three shapes
    decls = defaultdict(set)   # callee -> {(inMethod, line, lvalue)}
    assigns = defaultdict(set)  # callee -> {(inMethod, line)}
    files_read = []

    for path in argv[1:]:
        try:
            text = open(path, errors='replace').read()
        except OSError as exc:
            print(f'skip {path}: {exc}', file=sys.stderr)
            continue
        files_read.append(path)
        for line in text.splitlines():
            if '[owned-bind]' in line:
                seen_notes[0] += 1
            m = ASSIGN_RE.search(line)
            if m:
                assigns[strip_generics(m.group('callee'))].add(
                    (strip_generics(m.group('inm')), int(m.group('line'))))
                continue
            m = DECL_RE.search(line)
            if m:
                decls[strip_generics(m.group('callee'))].add(
                    (strip_generics(m.group('inm')), int(m.group('line')),
                     m.group('lvalue')))
                continue
            m = SIZING_RE.search(line)
            if m:
                decls[strip_generics(m.group('callee'))].add(
                    (strip_generics(m.group('inm')), int(m.group('line')), '?'))
                continue
            if '[owned-bind]' in line:
                unparsed.append(line.strip())

    if unparsed:
        print(f'FATAL: {len(unparsed)} of {seen_notes[0]} [owned-bind] notes did '
              f'not parse. A partial parse prints a confident, SHORT number —'
              f' which is exactly how the wildcard-instantiation records '
              f'(`Tensor<?>.zerosLike`) were dropped from a 1694-site count '
              f'that should have read 1791. Fix the pattern, do not report.',
              file=sys.stderr)
        for u in unparsed[:5]:
            print('  ' + u, file=sys.stderr)
        return 3

    n_decl = sum(len(v) for v in decls.values())
    n_assign = sum(len(v) for v in assigns.values())

    out = []
    out.append('# Owned-bind migration worklist (8.2.7)')
    out.append('')
    out.append(f'**{n_decl} declaration sites across {len(decls)} callees** — '
               f'what 8.2.7 rejects, and what this migration fixes.')
    out.append('')
    out.append(f'**{n_assign} assignment sites across {len(assigns)} callees** '
               '— counted, NOT rejected. §4.6\'s wording covers them; 8.2.7\'s '
               'measurement did not. See 8.2.12.')
    out.append('')
    out.append('Generated by `tools/ownership/report_owned_binds.py`. Each '
               'declaration row is `T x = f()` where `f` returns `#T` — the '
               'title moves, and nothing at that line says so.')
    out.append('')
    out.append('The fix is one character in nearly every case: '
               '`int8[] w = s.toBytes()` becomes `int8[] w #= s.toBytes()`.')
    out.append('')
    out.append('## Coverage')
    out.append('')
    out.append('Only what these builds compiled. A method no build reached is '
               'a method nobody measured.')
    out.append('')
    for path in files_read:
        out.append(f'- `{path}`')
    out.append('')

    out.append('## Declaration sites, by callee')
    out.append('')
    for callee in sorted(decls, key=lambda c: (-len(decls[c]), c)):
        sites = sorted(decls[callee])
        out.append(f'### `{callee}` — {len(sites)}')
        out.append('')
        out.append('| receiving method | line | lvalue |')
        out.append('| --- | --- | --- |')
        for inm, line, lvalue in sites:
            out.append(f'| `{inm}` | {line} | `{lvalue}` |')
        out.append('')

    if assigns:
        out.append('## Assignment sites (sizing only — 8.2.12)')
        out.append('')
        out.append('| callee | receiving method | line |')
        out.append('| --- | --- | --- |')
        for callee in sorted(assigns, key=lambda c: (-len(assigns[c]), c)):
            for inm, line in sorted(assigns[callee]):
                out.append(f'| `{callee}` | `{inm}` | {line} |')
        out.append('')

    print('\n'.join(out))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
