#!/usr/bin/env python3
"""
report_captured_borrows.py — turn a warn-mode harvest into the 3.3.3 worklist.

stdlib-ownership-convention plan, 3.3.3. Unit 3's check landed error-first; the
static audit had classified 10 sites and the gate then found 76 failures it had
never seen. The lesson recorded there is that only a BUILD enumerates these,
because the check sees captures through straight-line locals that no source-shape
pass recognises. So the input here is the compiler's own notes, emitted by

    CAJETA_CAPTURED_BORROW=warn cajeta build 2> harvest.log

as

    cajeta: note: [captured-borrow] <class>.<method>:<line> param=<p> src=<s> \\
        into=<dest> type=<T>

Sites are unioned across logs and deduped: one method compiles once per module
that pulls it in and once per library build, so raw counts triple-count.

The output groups by CLASS, because that is how the migration is actually
performed — a class's captures are one decision about that class's contract
(does it keep what it is handed?), and splitting them across commits is how a
half-migrated type ends up with two conventions.

Usage: report_captured_borrows.py <harvest.log> [more.log ...] > worklist.md
"""

import re
import sys
from collections import defaultdict

NOTE_RE = re.compile(
    r'\[captured-borrow\] (?P<key>[\w.$<>]*)\.(?P<method>[\w$<>]+):(?P<line>-?\d+) '
    r'param=(?P<param>\S+) src=(?P<src>\S+) into=(?P<into>.*?) type=(?P<type>\S+)$')

GENERIC_RE = re.compile(r'<[^<>]*>')


def strip_generics(name):
    """`Table<cajeta.lang.String>` -> `Table`.

    Same normalisation 8.1.1's report needed: one generic class instantiated
    five ways is ONE class to migrate, and counting instantiations inflated
    that inventory before this was added.
    """
    prev = None
    while prev != name:
        prev = name
        name = GENERIC_RE.sub('', name)
    return name


def main(argv):
    if len(argv) < 2:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    # class -> set of (method, line, param, src, into, type)
    by_class = defaultdict(set)
    files_read = []
    for path in argv[1:]:
        try:
            with open(path, errors='replace') as fh:
                text = fh.read()
        except OSError as exc:
            print(f'skip {path}: {exc}', file=sys.stderr)
            continue
        files_read.append(path)
        for line in text.splitlines():
            m = NOTE_RE.search(line)
            if not m:
                continue
            cls = strip_generics(m.group('key'))
            by_class[cls].add((
                m.group('method'), int(m.group('line')), m.group('param'),
                m.group('src'), m.group('into'), strip_generics(m.group('type'))))

    total = sum(len(v) for v in by_class.values())
    methods = len({(c, s[0]) for c, v in by_class.items() for s in v})

    out = []
    out.append('# Captured-borrow migration worklist (3.3.3)')
    out.append('')
    out.append(f'**{total} distinct capture sites across {methods} methods '
               f'in {len(by_class)} classes.**')
    out.append('')
    out.append('Generated by `tools/ownership/report_captured_borrows.py` from a '
               '`CAJETA_CAPTURED_BORROW=warn` harvest. Each row is a plain (`=`) '
               'store of a borrowed parameter into a field or element — the '
               'callee keeping what the caller only lent.')
    out.append('')
    out.append('The three sanctioned fixes, in the order to try them:')
    out.append('')
    out.append('1. **`#T` on the parameter** — the API really does keep the '
               'value, so say so and make every call site surrender it.')
    out.append('2. **`#=` on the store** — the type is a SINK whose caller '
               'chooses per call (the `ArrayList.add` model, spec §2.3). No '
               'signature change; the store form is the opt-out.')
    out.append('3. **copy** — the API keeps a value it was only shown.')
    out.append('')
    out.append('## Coverage')
    out.append('')
    out.append('Only what these builds compiled. A class no build reached is a '
               'class nobody measured — not a class with no captures.')
    out.append('')
    for path in files_read:
        out.append(f'- `{path}`')
    out.append('')
    out.append('## Sites')
    out.append('')

    for cls in sorted(by_class, key=lambda c: (-len(by_class[c]), c)):
        sites = sorted(by_class[cls], key=lambda s: (s[0], s[1]))
        out.append(f'### `{cls}` — {len(sites)}')
        out.append('')
        out.append('| method | line | parameter | into | type |')
        out.append('| --- | --- | --- | --- | --- |')
        for method, line, param, src, into, typ in sites:
            via = param if param == src else f'{param} (via `{src}`)'
            out.append(f'| `{method}` | {line} | `{via}` | {into} | `{typ}` |')
        out.append('')

    print('\n'.join(out))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
