# EmbedStdlib.cmake — build-time embedder for the cajeta stdlib.
#
# Invoked from src/CMakeLists.txt's add_custom_command so the embed
# cpp regenerates whenever a stdlib .cajeta source changes. Was at
# configure time previously; that meant editing a .cajeta file then
# running `ninja` left the embed stale until `cmake .` re-ran.
#
# Inputs (passed as -D args):
#   MANIFEST    — path to a text file with one absolute source path per line.
#                 Configure-time CMakeLists writes this manifest in lockstep
#                 with the glob it builds; passing the list directly through
#                 -DLIST=a;b;c collapses the semicolons to argv-splits.
#   STDLIB_ROOT — root used to compute relative paths in the manifest.
#   EMBED_OUT   — output .cpp file path.
#
# Output: a single .cpp that defines cajeta::stdlib::g_files and
# g_fileCount, matching the layout the Compiler reads at parse time.

if (NOT MANIFEST OR NOT STDLIB_ROOT OR NOT EMBED_OUT)
    message(FATAL_ERROR "EmbedStdlib.cmake: MANIFEST, STDLIB_ROOT, EMBED_OUT all required")
endif()

file(STRINGS "${MANIFEST}" CAJETA_STDLIB_FILES)
list(LENGTH CAJETA_STDLIB_FILES CAJETA_STDLIB_COUNT)

file(WRITE  "${EMBED_OUT}" "// AUTO-GENERATED by cmake/EmbedStdlib.cmake. Do not edit.\n")
file(APPEND "${EMBED_OUT}" "#include <cstddef>\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "namespace cajeta { namespace stdlib {\n")
file(APPEND "${EMBED_OUT}" "\n")

set(literal_index 0)
foreach(src_path ${CAJETA_STDLIB_FILES})
    file(READ "${src_path}" src_content)
    file(APPEND "${EMBED_OUT}"
         "static const char g_src_${literal_index}[] = R\"CAJEMB(${src_content})CAJEMB\";\n")
    math(EXPR literal_index "${literal_index} + 1")
endforeach()

file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "struct StdlibFile {\n")
file(APPEND "${EMBED_OUT}" "    const char* relativePath;\n")
file(APPEND "${EMBED_OUT}" "    const char* content;\n")
file(APPEND "${EMBED_OUT}" "    size_t contentBytes;\n")
file(APPEND "${EMBED_OUT}" "};\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "extern const StdlibFile g_files[] = {\n")

set(literal_index 0)
foreach(src_path ${CAJETA_STDLIB_FILES})
    file(RELATIVE_PATH rel_path "${STDLIB_ROOT}" "${src_path}")
    file(READ "${src_path}" src_content)
    string(LENGTH "${src_content}" content_bytes)
    file(APPEND "${EMBED_OUT}"
         "    { \"${rel_path}\", g_src_${literal_index}, ${content_bytes} },\n")
    math(EXPR literal_index "${literal_index} + 1")
endforeach()

file(APPEND "${EMBED_OUT}" "};\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "extern const size_t g_fileCount = ${CAJETA_STDLIB_COUNT};\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "}}  // namespace cajeta::stdlib\n")
