## EmbedInitTemplates.cmake — build-time embedder for `cajeta init`
## archetype templates.
##
## Reads `samples/buildtool/<type>/` trees and emits a single .cpp
## containing every file's bytes as a raw string literal, indexed by
## (template-name, relative-path). The `cajeta init` command pulls
## from these embedded bytes — no on-disk lookup at runtime.
##
## Run from src/CMakeLists.txt's add_custom_command. Mirrors the
## design of cmake/EmbedStdlib.cmake (manifest file passed by path,
## not -D list, so semicolons in paths survive sub-cmake quoting).
##
## Inputs (passed as -D args):
##   MANIFEST    — text file, one TAB-separated row per embedded file:
##                 `<template-name>\t<relative-path>\t<absolute-source-path>`
##                 Rows for the same template-name MUST appear in a
##                 contiguous block; output preserves manifest order.
##   EMBED_OUT   — output .cpp path.
##
## Output: defines
##   cajeta::buildtool::g_initTemplateFiles[]   — flat file table
##   cajeta::buildtool::g_initTemplates[]       — per-template slice
##   cajeta::buildtool::g_initTemplateCount     — number of templates
## Hand-written InitTemplates.cpp wraps these in a typed API.

if (NOT MANIFEST OR NOT EMBED_OUT)
    message(FATAL_ERROR "EmbedInitTemplates.cmake: MANIFEST and EMBED_OUT required")
endif()

file(STRINGS "${MANIFEST}" CAJETA_INIT_ROWS)
list(LENGTH CAJETA_INIT_ROWS CAJETA_INIT_ROW_COUNT)

file(WRITE  "${EMBED_OUT}" "// AUTO-GENERATED by cmake/EmbedInitTemplates.cmake. Do not edit.\n")
file(APPEND "${EMBED_OUT}" "#include <cstddef>\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "namespace cajeta { namespace buildtool {\n")
file(APPEND "${EMBED_OUT}" "\n")

# Pass 1: emit per-file content literals + accumulate per-template
# membership lists. The literal delimiter `CAJTPL` is chosen so that
# template files never contain `)CAJTPL"`; this is asserted at the
# CMake level so a careless add to samples/ fails build instead of
# producing malformed C++.
set(file_index 0)
set(current_template "")
set(template_names "")
set(template_first_indices "")
set(template_file_counts "")
set(template_files_in_current 0)

foreach(row ${CAJETA_INIT_ROWS})
    # Split row on tabs. CMake's STRING(REPLACE ...) is the simplest
    # tokenizer; we then split on semicolons (CMake's list separator).
    string(REPLACE "\t" ";" tokens "${row}")
    list(GET tokens 0 tname)
    list(GET tokens 1 trelpath)
    list(GET tokens 2 tabspath)

    if (NOT tname STREQUAL current_template)
        if (NOT current_template STREQUAL "")
            list(APPEND template_file_counts ${template_files_in_current})
        endif()
        set(current_template "${tname}")
        list(APPEND template_names "${tname}")
        list(APPEND template_first_indices ${file_index})
        set(template_files_in_current 0)
    endif()

    file(READ "${tabspath}" file_content)

    # Detect raw-string delimiter collision early. Without this, a
    # source file containing the literal sequence `)CAJTPL"` would
    # silently terminate the raw string mid-content.
    string(FIND "${file_content}" ")CAJTPL\"" delim_clash)
    if (NOT delim_clash EQUAL -1)
        message(FATAL_ERROR
            "EmbedInitTemplates: source file ${tabspath} contains the literal "
            "string ')CAJTPL\"' which collides with the raw-string delimiter. "
            "Rename CAJTPL in EmbedInitTemplates.cmake AND InitTemplates.cpp "
            "to a token that doesn't appear in this content.")
    endif()

    string(LENGTH "${file_content}" content_bytes)
    file(APPEND "${EMBED_OUT}"
         "static const char g_initFile_${file_index}[] = R\"CAJTPL(${file_content})CAJTPL\";\n")

    math(EXPR file_index "${file_index} + 1")
    math(EXPR template_files_in_current "${template_files_in_current} + 1")
endforeach()

# Close out the trailing template.
if (NOT current_template STREQUAL "")
    list(APPEND template_file_counts ${template_files_in_current})
endif()

list(LENGTH template_names template_count)

# Pass 2: emit the per-file table. Path strings live inline next to
# their content pointer; no separate string table.
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "struct InitTemplateFileRow {\n")
file(APPEND "${EMBED_OUT}" "    const char* relativePath;\n")
file(APPEND "${EMBED_OUT}" "    const char* content;\n")
file(APPEND "${EMBED_OUT}" "    size_t      contentBytes;\n")
file(APPEND "${EMBED_OUT}" "};\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "extern const InitTemplateFileRow g_initTemplateFiles[] = {\n")

set(file_index 0)
foreach(row ${CAJETA_INIT_ROWS})
    string(REPLACE "\t" ";" tokens "${row}")
    list(GET tokens 1 trelpath)
    list(GET tokens 2 tabspath)
    file(READ "${tabspath}" file_content)
    string(LENGTH "${file_content}" content_bytes)
    file(APPEND "${EMBED_OUT}"
         "    { \"${trelpath}\", g_initFile_${file_index}, ${content_bytes} },\n")
    math(EXPR file_index "${file_index} + 1")
endforeach()
file(APPEND "${EMBED_OUT}" "};\n")
file(APPEND "${EMBED_OUT}" "\n")

# Pass 3: emit the per-template slice table.
file(APPEND "${EMBED_OUT}" "struct InitTemplateRow {\n")
file(APPEND "${EMBED_OUT}" "    const char* name;\n")
file(APPEND "${EMBED_OUT}" "    size_t      firstFile;\n")
file(APPEND "${EMBED_OUT}" "    size_t      fileCount;\n")
file(APPEND "${EMBED_OUT}" "};\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "extern const InitTemplateRow g_initTemplates[] = {\n")

set(i 0)
foreach(tname ${template_names})
    list(GET template_first_indices ${i} first)
    list(GET template_file_counts   ${i} count)
    file(APPEND "${EMBED_OUT}"
         "    { \"${tname}\", ${first}, ${count} },\n")
    math(EXPR i "${i} + 1")
endforeach()
file(APPEND "${EMBED_OUT}" "};\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "extern const size_t g_initTemplateCount = ${template_count};\n")
file(APPEND "${EMBED_OUT}" "\n")
file(APPEND "${EMBED_OUT}" "}}  // namespace cajeta::buildtool\n")
