#include "GeneratedCode.h"

#include <vector>

namespace cajeta {

    namespace {
        struct Cursor {
            const std::string* file;
            int line;
            int column;
        };

        thread_local std::vector<GenerationSite> g_sites;
        thread_local std::vector<Cursor> g_cursors;
    }

    std::string synthesizerVia(const std::string& label) {
        std::string out;
        for (char c : label) {
            if (c >= 'A' && c <= 'Z') {
                if (!out.empty()) out += '-';
                out += static_cast<char>(c - 'A' + 'a');
            } else {
                out += c;
            }
        }
        return out + "-synthesizer";
    }

    GenerationScope::GenerationScope(const GenerationSite& site) { g_sites.push_back(site); }

    GenerationScope::~GenerationScope() { g_sites.pop_back(); }

    const GenerationSite* currentGenerationSite() {
        if (g_sites.empty() || g_sites.back().via.empty()) return nullptr;
        return &g_sites.back();
    }

    RequestCursor::RequestCursor(const std::string& file, int line, int column) {
        g_cursors.push_back({&file, line, column});
    }

    RequestCursor::~RequestCursor() { g_cursors.pop_back(); }

    SourceSite currentRequestSite() {
        if (auto* site = currentGenerationSite()) {
            if (site->request.known()) return site->request;
        }
        if (g_cursors.empty() || g_cursors.back().line <= 0) return {};
        const Cursor& c = g_cursors.back();
        return {*c.file, c.line, c.column};
    }

    GeneratedOrigin applyGenerationSite(const GenerationSite& site,
                                        std::string& file, int& line, int& column) {
        GeneratedOrigin g;
        g.via = site.via;
        if (!site.anchorOnly && line > 0) {
            g.fromFile = file.empty() ? site.innerFile : file;
            g.fromLine = line + site.lineDelta;
            g.fromColumn = column;
        } else if (site.anchor.known()) {
            g.fromFile = site.anchor.file;
            g.fromLine = site.anchor.line;
            g.fromColumn = site.anchor.column;
        }
        if (site.request.known()) {
            file = site.request.file;
            line = site.request.line;
            column = site.request.column;
        } else if (g.fromLine > 0) {
            file = g.fromFile;
            line = g.fromLine;
            column = g.fromColumn;
        }
        return g;
    }

    std::string generatedClause(const GeneratedOrigin& origin) {
        if (origin.via.empty()) return "";
        std::string s = " (in code generated by " + origin.via;
        if (!origin.fromFile.empty() && origin.fromLine > 0) {
            s += " from " + origin.fromFile + ":" + std::to_string(origin.fromLine);
        }
        return s + ")";
    }

    void Exception::stampGenerated() {
        if (auto* site = currentGenerationSite()) {
            generated = applyGenerationSite(*site, file, line, column);
        }
    }

} // namespace cajeta
